// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  missionId: __t.u64().name("mission_id"),
  playerIdentity: __t.identity().name("player_identity"),
  playerName: __t.string().name("player_name"),
  imageUrl: __t.string().name("image_url"),
  createdAt: __t.timestamp().name("created_at"),
});
