// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerIdentity: __t.identity().name("player_identity"),
  playerName: __t.string().name("player_name"),
  taskText: __t.string().name("task_text"),
  startedAt: __t.timestamp().name("started_at"),
  durationSeconds: __t.u32().name("duration_seconds"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
