// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteMissionReducer from "../complete_mission_reducer";
import DevClearWorldReducer from "../dev_clear_world_reducer";
import FailMissionReducer from "../fail_mission_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import JoinWorldReducer from "../join_world_reducer";
import StartMissionReducer from "../start_mission_reducer";

export type CompleteMissionParams = __Infer<typeof CompleteMissionReducer>;
export type DevClearWorldParams = __Infer<typeof DevClearWorldReducer>;
export type FailMissionParams = __Infer<typeof FailMissionReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinWorldParams = __Infer<typeof JoinWorldReducer>;
export type StartMissionParams = __Infer<typeof StartMissionReducer>;

